# Keep upstream pristine and build only the qualified standard Android CPU variants.
option(LIP_GGML_DOTPROD "Experimental standard ARM DOTPROD module" OFF)
set(_lip_metadata_path "${CMAKE_CURRENT_LIST_DIR}/ggml-android-dotprod.json")
file(READ "${_lip_metadata_path}" _lip_metadata)
string(JSON _lip_pin GET "${_lip_metadata}" pin)
get_filename_component(_lip_vendor "${CMAKE_CURRENT_LIST_DIR}/../../../../../third_party/whisper.cpp" REALPATH)
find_program(_lip_git NAMES git REQUIRED NO_CACHE)
execute_process(COMMAND "${_lip_git}" -C "${_lip_vendor}" rev-parse HEAD
    RESULT_VARIABLE _lip_result OUTPUT_VARIABLE _lip_actual_pin OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _lip_result EQUAL 0 OR NOT _lip_pin STREQUAL "306c88f4d1286aec1bf96e544632897886af5501"
   OR NOT _lip_actual_pin STREQUAL _lip_pin)
    message(FATAL_ERROR "Unexpected GGML DOTPROD source pin")
endif()
set(_lip_ggml_original "${_lip_vendor}/ggml")
set(_lip_patch "${CMAKE_CURRENT_LIST_DIR}/ggml-android-dotprod.patch")
foreach(_lip_kind IN ITEMS input patch license)
    string(JSON _lip_expected GET "${_lip_metadata}" "${_lip_kind}_sha256")
    if(_lip_kind STREQUAL "input")
        file(SHA256 "${_lip_ggml_original}/src/CMakeLists.txt" _lip_actual)
    elseif(_lip_kind STREQUAL "patch")
        file(SHA256 "${_lip_patch}" _lip_actual)
    else()
        file(SHA256 "${_lip_vendor}/LICENSE" _lip_actual)
    endif()
    if(NOT _lip_actual STREQUAL _lip_expected)
        message(FATAL_ERROR "Unexpected GGML DOTPROD ${_lip_kind} SHA256")
    endif()
endforeach()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_lip_patch}" "${_lip_metadata_path}")

set(_lip_ggml_generated "${CMAKE_CURRENT_BINARY_DIR}/ggml-dotprod")
file(GLOB_RECURSE _lip_files LIST_DIRECTORIES FALSE RELATIVE "${_lip_ggml_original}" "${_lip_ggml_original}/*")
list(SORT _lip_files)
set(_lip_tree "")
foreach(_lip_file IN LISTS _lip_files)
    file(SHA256 "${_lip_ggml_original}/${_lip_file}" _lip_hash)
    string(APPEND _lip_tree "${_lip_file}:${_lip_hash}\n")
endforeach()
string(SHA256 _lip_actual "${_lip_tree}")
string(JSON _lip_expected GET "${_lip_metadata}" input_tree_sha256)
if(NOT _lip_actual STREQUAL _lip_expected)
    message(FATAL_ERROR "Unexpected GGML DOTPROD input tree SHA256")
endif()
foreach(_lip_file IN LISTS _lip_files)
    configure_file("${_lip_ggml_original}/${_lip_file}" "${_lip_ggml_generated}/${_lip_file}" COPYONLY)
endforeach()
find_program(_lip_patch_program NAMES patch REQUIRED NO_CACHE)
execute_process(COMMAND "${_lip_patch_program}" -f -s "${_lip_ggml_generated}/src/CMakeLists.txt" "${_lip_patch}"
    RESULT_VARIABLE _lip_result OUTPUT_VARIABLE _lip_stdout ERROR_VARIABLE _lip_stderr)
if(NOT _lip_result EQUAL 0)
    message(FATAL_ERROR "GGML DOTPROD patch failed: ${_lip_stdout}${_lip_stderr}")
endif()
file(GLOB_RECURSE _lip_generated_files LIST_DIRECTORIES FALSE RELATIVE "${_lip_ggml_generated}" "${_lip_ggml_generated}/*")
list(SORT _lip_generated_files)
set(_lip_tree "")
foreach(_lip_file IN LISTS _lip_generated_files)
    file(SHA256 "${_lip_ggml_generated}/${_lip_file}" _lip_hash)
    string(APPEND _lip_tree "${_lip_file}:${_lip_hash}\n")
endforeach()
string(SHA256 _lip_actual "${_lip_tree}")
string(JSON _lip_expected GET "${_lip_metadata}" output_tree_sha256)
if(NOT _lip_actual STREQUAL _lip_expected)
    message(FATAL_ERROR "Unexpected GGML DOTPROD output tree SHA256")
endif()

set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(GGML_BACKEND_DL ON CACHE BOOL "" FORCE)
set(GGML_CPU_ARM_ARCH "" CACHE STRING "" FORCE)
if(ANDROID_ABI STREQUAL "arm64-v8a")
    set(GGML_CPU_ALL_VARIANTS ON CACHE BOOL "" FORCE)
    set(_lip_cpu_targets ggml-cpu-android_armv8.0_1)
    if(LIP_GGML_DOTPROD)
        list(APPEND _lip_cpu_targets ggml-cpu-android_armv8.2_1)
    endif()
elseif(ANDROID_ABI STREQUAL "x86_64")
    set(GGML_CPU_ALL_VARIANTS OFF CACHE BOOL "" FORCE)
    set(_lip_cpu_targets ggml-cpu)
else()
    message(FATAL_ERROR "Unsupported CPU experiment ABI: ${ANDROID_ABI}")
endif()
if(NOT CMAKE_LIBRARY_OUTPUT_DIRECTORY)
    message(FATAL_ERROR "CPU experiment requires AGP's per-ABI library output directory")
endif()
# MODULE artifacts must be in AGP's native model/output directory, not Whisper's bin.
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
add_subdirectory("${_lip_ggml_generated}" ggml EXCLUDE_FROM_ALL)
target_link_libraries(ggml PRIVATE dl)
set_target_properties(ggml ggml-base ${_lip_cpu_targets} PROPERTIES
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}")
