# Keep the submodule pristine; patch only the configure-generated translation unit.
set(_provenance "${CMAKE_CURRENT_LIST_DIR}/whisper-scheduler-abort.json")
file(READ "${_provenance}" _metadata)
string(JSON _pin GET "${_metadata}" pin)
if(NOT _pin STREQUAL "306c88f4d1286aec1bf96e544632897886af5501")
    message(FATAL_ERROR "Unexpected Whisper cancellation patch pin")
endif()
get_filename_component(_original
    "${CMAKE_CURRENT_LIST_DIR}/../../../../../third_party/whisper.cpp/src/whisper.cpp" REALPATH)
set(_patch "${CMAKE_CURRENT_LIST_DIR}/whisper-scheduler-abort.patch")
foreach(_kind IN ITEMS input patch)
    string(JSON _expected GET "${_metadata}" "${_kind}_sha256")
    if(_kind STREQUAL "input")
        file(SHA256 "${_original}" _actual)
    else()
        file(SHA256 "${_patch}" _actual)
    endif()
    if(NOT _actual STREQUAL _expected)
        message(FATAL_ERROR "Unexpected Whisper cancellation ${_kind} SHA256")
    endif()
endforeach()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_patch}" "${_provenance}")

set(_generated "${CMAKE_CURRENT_BINARY_DIR}/whisper-cancel/whisper.cpp")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/whisper-cancel")
configure_file("${_original}" "${_generated}" COPYONLY)
find_program(_patch_program NAMES patch REQUIRED NO_CACHE)
execute_process(COMMAND "${_patch_program}" -f -s "${_generated}" "${_patch}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
if(NOT _result STREQUAL "0")
    message(FATAL_ERROR "Whisper cancellation patch failed: ${_stdout}${_stderr}")
endif()
string(JSON _expected GET "${_metadata}" output_sha256)
file(SHA256 "${_generated}" _actual)
if(NOT _actual STREQUAL _expected)
    message(FATAL_ERROR "Unexpected patched Whisper SHA256")
endif()

get_target_property(_source_dir whisper SOURCE_DIR)
get_target_property(_sources whisper SOURCES)
set(_original_count 0)
foreach(_source IN LISTS _sources)
    get_filename_component(_absolute "${_source}" REALPATH BASE_DIR "${_source_dir}")
    if(_absolute STREQUAL _original)
        math(EXPR _original_count "${_original_count} + 1")
    elseif(_absolute STREQUAL _generated)
        message(FATAL_ERROR "Patched Whisper source already attached")
    endif()
endforeach()
if(NOT _original_count EQUAL 1)
    message(FATAL_ERROR "Expected exactly one pristine Whisper translation unit")
endif()
# Source properties are directory-scoped, unlike target includes and compile options.
set_source_files_properties("${_original}" TARGET_DIRECTORY whisper PROPERTIES HEADER_FILE_ONLY TRUE)
get_source_file_property(_header_only "${_original}" TARGET_DIRECTORY whisper HEADER_FILE_ONLY)
if(NOT _header_only)
    message(FATAL_ERROR "Pristine Whisper translation unit would still compile")
endif()
target_sources(whisper PRIVATE "${_generated}")
